// GENERATED by scripts/prepare-assets.mjs — do not edit by hand.
// Source images live in /pictures. Re-run `npm run assets` after adding photos.

export type GalleryFrame = {
  id: string;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  /** Landscape frames occupy a wider slot in the horizontal track. */
  orientation: "portrait" | "landscape" | "square";
};

export const portrait = {
  src: "/images/priyanshu.jpg",
  width: 963,
  height: 1280,
  blurDataURL: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwAgCdASoLAA4AA4BaJQBOgCMDOVBeqTRoAAD+8ae2xhQb4cFtv7e0J3MCXzYzpa/+veyj7N/FT1AHbsczzuq2fZzt+HxInsoKoShs0SwEwplrPP6Hgyc7tvH8gd/yAAA=",
  alt: "Priyanshu Srivastava",
} as const;

export const gallery: GalleryFrame[] = [
  {
    "id": "frame-01",
    "src": "/images/gallery/frame-01.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoLAA4AA4BaJagCdADbpCRLgQpgAP2QLwJOJfeLazDXL8lCgP7LLZ77yZsGeZrl7hDMgXOeeNbltszqWtdIm9fRl5D3SzX1qTgbxW/vXSaqoAAA",
    "orientation": "portrait"
  },
  {
    "id": "frame-02",
    "src": "/images/gallery/frame-02.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoLAA4AA4BaJaACdAEfbSAY0SAA/u7uXO9OV1LLfQyLrYaUeM923+ldsdxzVwAeZV1ffZ92FfkQwYcVO03ARcK/11C2YrXEdUYAAA==",
    "orientation": "portrait"
  },
  {
    "id": "frame-03",
    "src": "/images/gallery/frame-03.jpg",
    "width": 1600,
    "height": 1204,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAAAQAgCdASoOAAsAA4BaJQBOgCFsfFrp032AAP74Uh+vmm7NdSCqnovjU9RyCOPuKPXu+UA+lDJd62AA",
    "orientation": "landscape"
  },
  {
    "id": "frame-04",
    "src": "/images/gallery/frame-04.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoLAA4AA4BaJQBOgBQNevxQAADf80zEgy69QP6TnOD5shjYc1NaGWgekRTXq15tdLPTPAAA",
    "orientation": "portrait"
  },
  {
    "id": "frame-05",
    "src": "/images/gallery/frame-05.jpg",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoLAA4AA4BaJZwAAudL3i4jeAD++E3frcQ+JDA+Lx0QL7Kh8QY8xeT0bmhbTV2M0/HfVcwCgAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-06",
    "src": "/images/gallery/frame-06.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAQCdASoLAA4AA4BaJagCdABdSAD3sHfT0Aq9Ko+14NSSBbAX53OigUd+jrey8pbxwEXyOct2QWXwAAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-07",
    "src": "/images/gallery/frame-07.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADQAQCdASoLAA4AA4BaJYwAAudRNMHKwAD+9IN2tuINBFXaw8jhmkZdl+I/Dg+AncbeF8slJn6guYB/ReiI5DcbcYTQAA==",
    "orientation": "portrait"
  },
  {
    "id": "frame-08",
    "src": "/images/gallery/frame-08.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoLAA4AA4BaJQBOgCIj+QciFtsAAP7xuMZRVPm2/RfxIigMtIoWMLcz0q1z6XmMeGkWX4iPDzxT6i4vUBMr/oAA",
    "orientation": "portrait"
  },
  {
    "id": "frame-09",
    "src": "/images/gallery/frame-09.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADQAQCdASoLAA4AA4BaJbACdACRW/mRAAD61KP2qZa1Jnkrh3yvugo917ZT/9uKryJM4hg75BbGIWnK25BZe8Rkdc/1g7PcMZkBQAAA",
    "orientation": "portrait"
  },
  {
    "id": "frame-10",
    "src": "/images/gallery/frame-10.jpg",
    "width": 1280,
    "height": 1104,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwAgCdASoOAAwAA4BaJbACdADiZnbbCeoiAAD9jVhe7CceFCYHer1g2UbkrWHl692b+ZVBBYH3evWek2le4bG9whOEgTurP2qSCIYiRA6jJuVk4AA=",
    "orientation": "landscape"
  },
  {
    "id": "frame-11",
    "src": "/images/gallery/frame-11.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoLAA4AA4BaJZQAAln32TiAAAD8/BeNsurKq/2FHgNSMrGbxtozpWkijj/k9NI4fGRZ0xkFU0d1i+b644Hx6yjTaW1+q6bEUAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-12",
    "src": "/images/gallery/frame-12.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoLAA4AA4BaJZACdAEPCy72AAD+82FJ5ut8+A2aDpDwxPrtQorsF9G9kT/4MenJspLI7MdFEGfhBYpEFQaKAvsnQAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-13",
    "src": "/images/gallery/frame-13.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAQCdASoLAA4AA4BaJZwAAuddUNoDgAD++Qwqwyo2hF7VYi24PwCGIMAPgAAA",
    "orientation": "portrait"
  },
  {
    "id": "frame-14",
    "src": "/images/gallery/frame-14.jpg",
    "width": 1200,
    "height": 1600,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoLAA4AA4BaJYgCdAYuHczaTkr4AP7u6hxtGrxqvzhR1Vtcxm7eh67wP1Tiw4d2rvHSYTO7c2NTtc5E0ITU9l29KNCmMH4n6Z6GirK3UZAeRlTruok15Re0AAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-15",
    "src": "/images/gallery/frame-15.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoLAA4AA4BaJQBOgCHZsmVi1AD+9CMNYx+ahPHl8XOqXjoy9T5/WXIHFlIm0C3D7uRef6AA",
    "orientation": "portrait"
  },
  {
    "id": "frame-16",
    "src": "/images/gallery/frame-16.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoLAA4AA4BaJYgCdADcdq3MEWAA/j8Njk/LyAU3s/NfVBNnvpk9R6/z7Pzno9aXyIUdrWUQwIQlqP0tboIt23XzG5s4miYfgAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-17",
    "src": "/images/gallery/frame-17.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAAAwAgCdASoLAA4AA4BaJbACdAEfAZ1flkGwYAD+ItpGVn71+CtDjIyxZRfLVzbP0UN0sQvJR8bs9v8b2aGICdET1hycGftzSkXvz6gm3B37/sxjwMAhmmJSZhHgAA==",
    "orientation": "portrait"
  },
  {
    "id": "frame-18",
    "src": "/images/gallery/frame-18.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAQCdASoLAA4AA4BaJQBOgCHfyswtDAAA/vapFSRS+G7zb1hL045iLYsuF/ne3v85j5EzWAkNBCTWa/4lT1gr9Nu0F2/2CSyKYAAA",
    "orientation": "portrait"
  },
  {
    "id": "frame-19",
    "src": "/images/gallery/frame-19.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoLAA4AA4BaJYwCdAEQ/hQ9SqKAAP70JVrLPlNINqFxqGdwszHVVZ+p7xpy3WtxVkB9CqXI2gQBwREc0GAAAA==",
    "orientation": "portrait"
  },
  {
    "id": "frame-20",
    "src": "/images/gallery/frame-20.jpg",
    "width": 963,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADwAQCdASoLAA4AA4BaJYgCdAEPCnjAvgAA/vR0wlliOIn0ni5tUihQl4gG246HXZItiKUO/R32N8ae/9oKTnKzAAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-21",
    "src": "/images/gallery/frame-21.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoLAA4AA4BaJZQAAp1auMgwwdgAAP7qAYxi2X4T7/hUOaKRctSYWkbWjbWxk/fRg6wgEPRnETxhv51140jItnyxaTLFyNRE+ohLdZ1mlX29fmFLAdyogAywAAA=",
    "orientation": "portrait"
  },
  {
    "id": "frame-22",
    "src": "/images/gallery/frame-22.jpg",
    "width": 960,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAAAQAgCdASoLAA4AA4BaJYwCdAEOu+M90y0gAP7u2JKijpbPjuC1bgEBrBkL6YrPQavP6B76pip+FItYr3HhoPmHsAA=",
    "orientation": "portrait"
  }
];

export const galleryCount = gallery.length;
