/**
 * Copies /pictures into /public/images, optimises them, and emits the typed
 * gallery manifest (dimensions + blur placeholders) into data/gallery.ts.
 *
 * Run: npm run assets
 */
import { readdir, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "pictures");
const OUT_GALLERY = path.join(ROOT, "public", "images", "gallery");
const OUT_IMAGES = path.join(ROOT, "public", "images");
const MANIFEST = path.join(ROOT, "data", "gallery.ts");

const PORTRAIT_SRC = "Priyanshu(Me).jpg";
const MAX_EDGE = 1600;
const QUALITY = 82;

/** "shared image (2).jpg" sorts after "shared image.jpg" and before "(10)". */
function naturalIndex(name) {
  const m = name.match(/\((\d+)\)/);
  return m ? Number(m[1]) : 0;
}

async function blurDataUrl(input) {
  const buf = await sharp(input).resize(14, 14, { fit: "inside" }).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

async function emit(input, output) {
  const image = sharp(input).rotate();
  const { width = 0, height = 0 } = await image.metadata();
  await image
    .resize(MAX_EDGE, MAX_EDGE, { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: QUALITY, mozjpeg: true, progressive: true })
    .toFile(output);
  const out = await sharp(output).metadata();
  return { width: out.width ?? width, height: out.height ?? height };
}

async function main() {
  await mkdir(OUT_GALLERY, { recursive: true });

  const files = (await readdir(SRC)).filter((f) => /\.(jpe?g|png)$/i.test(f));
  const gallerySrc = files.filter((f) => f !== PORTRAIT_SRC).sort((a, b) => naturalIndex(a) - naturalIndex(b));

  const portraitOut = path.join(OUT_IMAGES, "priyanshu.jpg");
  const portrait = await emit(path.join(SRC, PORTRAIT_SRC), portraitOut);
  const portraitBlur = await blurDataUrl(portraitOut);

  const frames = [];
  for (const [i, file] of gallerySrc.entries()) {
    const id = String(i + 1).padStart(2, "0");
    const outPath = path.join(OUT_GALLERY, `frame-${id}.jpg`);
    const { width, height } = await emit(path.join(SRC, file), outPath);
    frames.push({
      id: `frame-${id}`,
      src: `/images/gallery/frame-${id}.jpg`,
      width,
      height,
      blurDataURL: await blurDataUrl(outPath),
    });
    process.stdout.write(`  frame-${id}  ${width}x${height}\n`);
  }

  const body = `// GENERATED by scripts/prepare-assets.mjs — do not edit by hand.
// Source images live in /pictures. Re-run \`npm run assets\` after adding photos.

export type GalleryFrame = {
  id: string;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
  /** Landscape frames occupy a wider slot in the horizontal track. */
  orientation: "portrait" | "landscape" | "square";
};

export const portrait = {
  src: "/images/priyanshu.jpg",
  width: ${portrait.width},
  height: ${portrait.height},
  blurDataURL: "${portraitBlur}",
  alt: "Priyanshu Srivastava",
} as const;

export const gallery: GalleryFrame[] = ${JSON.stringify(
    frames.map((f) => ({
      ...f,
      orientation: f.width / f.height > 1.1 ? "landscape" : f.width / f.height < 0.9 ? "portrait" : "square",
    })),
    null,
    2,
  )};

export const galleryCount = gallery.length;
`;

  await writeFile(MANIFEST, body, "utf8");
  console.log(`\n✓ ${frames.length} frames + portrait → public/images`);
  console.log(`✓ manifest → data/gallery.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
